### ISSUE TITLE
Veloerfassung: Zubehör

### ISSUE THREAD

**Issue by leandromeier** [thoemel/veloboerse#165]
Bisher konnte man bei Velozubehör auf der Quittung 'Zubehör' ankreuzen, wenn ein Velo Zubehör hatte. Jetzt kann man nur der Typ Velo, den es ist, oder Zubehör anwählen. Ich glaube es wäre gut wenn man bei einem Velo mit Zubehör das im Formular irgendwie noch vermerken könnte.

**Comment by thoemel** [comment]
Das würde ich von den PV-Leuten eintragen lassen. Nicht dass jemand Zusatzmaterial ankündigt und dann nicht abliefert. 
Das bedeutet, ich muss bei der Annahme auch das Bemerkungs-Feld anzeigen.

**Comment by leandromeier** [comment]
Ja dein Vorschlg tönt besser.
