### ISSUE TITLE
Zettel für ans Velo drucken

### ISSUE THREAD

**Issue by leandromeier** [thoemel/veloboerse#166]
Wenn ich als Benutzer nach Velo-Erfassung auf 'Zettel für ans Velo drucken' klicke, lande ich hier:
![grafik](https://user-images.githubusercontent.com/43414051/90309523-9bbfb580-dee9-11ea-99b2-625c05c27cb1.png)

**Comment by thoemel** [comment]
Nicht reproduzierbar oder gefixt
