### ISSUE TITLE
Quittung drucken

### ISSUE THREAD

**Issue by leandromeier** [thoemel/veloboerse#167]
Wenn ich im Ressort Annahme für ein angenommenes Velo die Quittung drucken will, lande ich auf dieser weissen Seite:
![grafik](https://user-images.githubusercontent.com/43414051/90309568-040e9700-deea-11ea-9f6a-6990c15e88ad.png)

**Comment by thoemel** [comment]
War ein Cache-Problem. Ist gelöst.
