### ISSUE TITLE
Händlerformular: Adressfeld aufsplitten

### ISSUE THREAD

**Issue by ghost** [thoemel/veloboerse#97]
Feld Adresse aufteilen in mehrere Felder:
Strasse
Hausnummer
Postleitzahl
Ort
-> Mit Rebecca schauen wie genau sie es haben will.

**Comment by thoemel** [comment]
Hoi markus

Ich bin dagegen, dieses feld aufzusplitten. Ich kenne keine gründe dafür.

Grüessli
Thömu

Thomas Schlegel
Lorrainestrasse 66
3014 Bern
078 604 59 98
